[meta]
name     = "Music Mania"
author   = "XertroV"
category = "Music"
version  = "0.9.1"

blocks = ["music-auto-toggler", "music-auto-toggler-dev"]

[script]
#__DEFINES__
# dependencies = ["MLHook", "MLFeedRaceData"]
dependencies = ["VehicleState"]
